main_sait/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('politika-konfidencialnosti/', views.konfiden, name='konfiden'),
    path('normativno-pravovie-documenti/', views.documents, name='documents'),
    path('kontacti/', views.contact, name='contact'),
    path('katalog/', views.price, name='price'),
]

main_sait/main_sait/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('services/', include('services.urls', namespace='services')),
    path('spravki/', include('spravki.urls', namespace='spravki')),
    path('profosmotri/', include('profi.urls', namespace='profi')),
    path('knigki/', include('knigki.urls', namespace='knigki')),
    path('akzii/', include('sale.urls', namespace='sale')),
    path('statii/', include('posts.urls', namespace='posts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_sait/spravki/urls.py
from django.urls import path

from . import views

app_name = 'spravki'

urlpatterns = [
    path('003-wy/', views.gibdd, name='gibdd'),
    path('gims/', views.gims, name='gims'),
    path('001-gsy/', views.gsy, name='gsy'),
    path('989n/', views.gstayna, name='gstayna'),
    path('spravki-086y/', views.spravki_086, name='spravki_086'),
    path(
        'spravki-086y/<slug:choice>',
        views.spravki_086_datail,
        name='spravki_086_datail'
    ),
    path('spravki-095y/', views.student_095, name='student_095'),
    path('spravki-sport/', views.spravki_sport, name='spravki_sport'),
    path(
        'spravki-sport/<slug:choice>',
        views.spravki_sport_datail,
        name='spravki_sport_datail'
    ),
    path('spravki-puteshestvij/', views.spravki_travel, name='spravki_travel'),
    path(
        'spravki-puteshestvij/<slug:choice>',
        views.spravki_travel_datail,
        name='spravki_travel_datail'
    ),
    path('bolnichnyj-list/', views.bolnichnij, name='bolnichnij'),
]

main_sait/spravki/models.py
from django.db import models


class Gibdd(models.Model):
    title = models.TextField(
        'Наименование услуги',
        help_text='Введите наименование услуги',
        max_length=100
    )
    price = models.TextField(
        'Цена',
        help_text='Введите цену справки',
        max_length=50
    )

    class Meta:
        verbose_name = 'Справки ГАИ'
        verbose_name_plural = 'Справки ГАИ'


class Gims(models.Model):
    title = models.TextField(
        'Наименование услуги',
        help_text='Введите наименование услуги',
        max_length=100
    )
    price = models.TextField(
        'Цена',
        help_text='Введите цену справки',
        max_length=50
    )

    class Meta:
        verbose_name = 'Справки ГИМС'
        verbose_name_plural = 'Справки ГИМС'


class Gsy(models.Model):
    title = models.TextField(
        'Наименование услуги',
        help_text='Введите наименование услуги',
        max_length=100
    )
    price = models.TextField(
        'Цена',
        help_text='Введите цену справки',
        max_length=50
    )

    class Meta:
        verbose_name = 'Справки Госслужба (001-ГС/у)'
        verbose_name_plural = 'Справки Госслужба (001-ГС/у)'


class Gstayna(models.Model):
    title = models.TextField(
        'Наименование услуги',
        help_text='Введите наименование услуги',
        max_length=100
    )
    price = models.TextField(
        'Цена',
        help_text='Введите цену справки',
        max_length=50
    )

    class Meta:
        verbose_name = 'Справки Гостайна (989н)'
        verbose_name_plural = 'Справки Госслужба (989н)'


class Spravka086_1(models.Model):
    CHOICES = (
        ('dlya-meditsinskikh-napravleniy', 'Медики'),
        ('na-dolzhnost-sudi', 'Судья'),
        ('dlya-raboty', 'Обычная'),
        ('dlya-postupleniya', 'Институт'),
    )
    choice = models.CharField(
        'Выбор справки 086',
        help_text='''Выберети нужную справку для
                   правильного отображения страницы''',
        max_length=100,
        null=True,
        choices=CHOICES
    )
    title = models.TextField(
        'Наименование услуги',
        help_text='Введите наименование услуги',
        max_length=100
    )
    price = models.TextField(
        'Цена',
        help_text='Введите цену справки',
        max_length=50
    )

    class Meta:
        verbose_name = 'Справки 086/у'
        verbose_name_plural = 'Справки 086/у'


class Spravka095_1(models.Model):
    title = models.TextField(
        'Наименование услуги',
        help_text='Введите наименование услуги',
        max_length=100
    )
    price = models.TextField(
        'Цена',
        help_text='Введите цену справки',
        max_length=50
    )

    class Meta:
        verbose_name = 'Справки 095/у'
        verbose_name_plural = 'Справки 095/у'


class Bassein(models.Model):
    CHOICES = (
        ('bassein', 'Бассейн'),
        ('sport', 'Спорт'),
        ('sabeg', 'Забег'),
        ('sapliv', 'Заплыв'),
    )
    choice = models.CharField(
        'Выбор справки спорт',
        help_text='''Выберети нужную справку для
                   правильного отображения страницы''',
        max_length=100,
        null=True,
        choices=CHOICES
    )
    title = models.TextField(
        'Наименование услуги',
        help_text='Введите наименование услуги',
        max_length=100
    )
    price = models.TextField(
        'Цена',
        help_text='Введите цену справки',
        max_length=50
    )

    class Meta:
        verbose_name = 'Справки для спорта'
        verbose_name_plural = 'Справки для спорта'


class Travel(models.Model):
    CHOICES = (
        ('sankarta', 'Санкарта'),
        ('sanatoriy', 'Санаторий'),
        ('sagranica', 'Заграница'),
    )
    choice = models.CharField(
        'Выбор справки для путешествий',
        help_text='''Выберети нужную справку для
                   правильного отображения страницы''',
        max_length=100,
        null=True,
        choices=CHOICES
    )
    title = models.TextField(
        'Наименование услуги',
        help_text='Введите наименование услуги',
        max_length=100
    )
    price = models.TextField(
        'Цена',
        help_text='Введите цену справки',
        max_length=50
    )

    class Meta:
        verbose_name = 'Справки для поездок'
        verbose_name_plural = 'Справки для поездок'


class Bolnichnij(models.Model):
    title = models.TextField(
        'Наименование услуги',
        help_text='Введите наименование услуги',
        max_length=100
    )
    price = models.TextField(
        'Цена',
        help_text='Введите цену справки',
        max_length=50
    )

    class Meta:
        verbose_name = 'Больничные листы'
        verbose_name_plural = 'Больничные листы'

main_sait/spravki/views.py
from asgiref.sync import sync_to_async
from django.shortcuts import get_object_or_404, render

from home.models import HomeTopInfo
from sale.models import Sale

from .models import (Bassein, Bolnichnij, Gibdd, Gims, Gstayna, Gsy,
                     Spravka086_1, Spravka095_1, Travel)

SAIT_INFO = HomeTopInfo.objects.all()


@sync_to_async
def gibdd(request):
    template = 'spravki/gibdd.html'
    info = SAIT_INFO
    sale_info = Sale.objects.filter(choice='spravki:gibdd')
    price = Gibdd.objects.all()
    context = {
        'info': info,
        'price': price,
        'sale_info': sale_info,
    }
    return render(request, template, context)


@sync_to_async
def gims(request):
    template = 'spravki/gims.html'
    info = SAIT_INFO
    sale_info = Sale.objects.filter(choice='spravki:gims')
    price = Gims.objects.all()
    context = {
        'info': info,
        'price': price,
        'sale_info': sale_info,
    }
    return render(request, template, context)


@sync_to_async
def gsy(request):
    template = 'spravki/gsy.html'
    info = SAIT_INFO
    sale_info = Sale.objects.filter(choice='spravki:gsy')
    price = Gsy.objects.all()
    context = {
        'info': info,
        'price': price,
        'sale_info': sale_info,
    }
    return render(request, template, context)


@sync_to_async
def gstayna(request):
    template = 'spravki/gstayna.html'
    info = SAIT_INFO
    sale_info = Sale.objects.filter(choice='spravki:gstayna')
    price = Gstayna.objects.all()
    context = {
        'info': info,
        'price': price,
        'sale_info': sale_info,
    }
    return render(request, template, context)


@sync_to_async
def spravki_086(request):
    template = 'spravki/spravki_086.html'
    info = SAIT_INFO
    sale_info = Sale.objects.filter(choice='spravki:spravki_086')
    price = Spravka086_1.objects.all()
    context = {
        'info': info,
        'price': price,
        'sale_info': sale_info,
    }
    return render(request, template, context)


@sync_to_async
def spravki_086_datail(request, choice):
    if choice == 'na-dolzhnost-sudi':
        template = 'spravki/086y/sudija.html'
        info = SAIT_INFO
        price = get_object_or_404(Spravka086_1, choice=choice)
        context = {
            'info': info,
            'price': price,
        }
        return render(request, template, context)
    elif choice == 'dlya-raboty':
        template = 'spravki/086y/naraboty.html'
        info = SAIT_INFO
        price = get_object_or_404(Spravka086_1, choice=choice)
        context = {
            'info': info,
            'price': price,
        }
        return render(request, template, context)
    elif choice == 'dlya-postupleniya':
        template = 'spravki/086y/student.html'
        info = SAIT_INFO
        price = get_object_or_404(Spravka086_1, choice=choice)
        context = {
            'info': info,
            'price': price,
        }
        return render(request, template, context)
    elif choice == 'dlya-meditsinskikh-napravleniy':
        template = 'spravki/086y/meditsina.html'
        info = SAIT_INFO
        price = get_object_or_404(Spravka086_1, choice=choice)
        context = {
            'info': info,
            'price': price,
        }
        return render(request, template, context)


@sync_to_async
def student_095(request):
    template = 'spravki/student_095.html'
    info = SAIT_INFO
    sale_info = Sale.objects.filter(choice='spravki:student_095')
    price = Spravka095_1.objects.all()
    context = {
        'info': info,
        'price': price,
        'sale_info': sale_info,
    }
    return render(request, template, context)


@sync_to_async
def spravki_sport(request):
    template = 'spravki/spravki_sport.html'
    info = SAIT_INFO
    sale_info = Sale.objects.filter(choice='spravki:spravki_sport')
    price = Bassein.objects.all()
    context = {
        'info': info,
        'price': price,
        'sale_info': sale_info,
    }
    return render(request, template, context)


@sync_to_async
def spravki_sport_datail(request, choice):
    if choice == 'bassein':
        template = 'spravki/sport/bassein.html'
        info = SAIT_INFO
        price = get_object_or_404(Bassein, choice=choice)
        context = {
            'info': info,
            'price': price,
        }
        return render(request, template, context)
    elif choice == 'sport':
        template = 'spravki/sport/sport.html'
        info = SAIT_INFO
        price = get_object_or_404(Bassein, choice=choice)
        context = {
            'info': info,
            'price': price,
        }
        return render(request, template, context)
    elif choice == 'sapliv':
        template = 'spravki/sport/sapliv.html'
        info = SAIT_INFO
        price = get_object_or_404(Bassein, choice=choice)
        context = {
            'info': info,
            'price': price,
        }
        return render(request, template, context)
    elif choice == 'sabeg':
        template = 'spravki/sport/sabeg.html'
        info = SAIT_INFO
        price = get_object_or_404(Bassein, choice=choice)
        context = {
            'info': info,
            'price': price,
        }
        return render(request, template, context)


@sync_to_async
def spravki_travel(request):
    template = 'spravki/spravki_travel.html'
    info = SAIT_INFO
    sale_info = Sale.objects.filter(choice='spravki:spravki_travel')
    price = Travel.objects.all()
    context = {
        'info': info,
        'price': price,
        'sale_info': sale_info,
    }
    return render(request, template, context)


@sync_to_async
def spravki_travel_datail(request, choice):
    if choice == 'sankarta':
        template = 'spravki/travel/sankarta.html'
        info = SAIT_INFO
        price = get_object_or_404(Travel, choice=choice)
        context = {
            'info': info,
            'price': price,
        }
        return render(request, template, context)
    elif choice == 'sanatoriy':
        template = 'spravki/travel/putevka.html'
        info = SAIT_INFO
        price = get_object_or_404(Travel, choice=choice)
        context = {
            'info': info,
            'price': price,
        }
        return render(request, template, context)
    elif choice == 'sagranica':
        template = 'spravki/travel/sagranica.html'
        info = SAIT_INFO
        price = get_object_or_404(Travel, choice=choice)
        context = {
            'info': info,
            'price': price,
        }
        return render(request, template, context)


@sync_to_async
def bolnichnij(request):
    template = 'spravki/bolnichnij.html'
    info = SAIT_INFO
    sale_info = Sale.objects.filter(choice='spravki:bolnichnij')
    price = Bolnichnij.objects.all()
    context = {
        'info': info,
        'price': price,
        'sale_info': sale_info,
    }
    return render(request, template, context)

main_sait/templates/spravki/spravki_086.html
{% extends 'base.html' %}
{% load static %}


{% block title%}
086/у справки в Медицинский центр МедикаФарм
{% endblock %}

{% block content %}


<div class="container col-xl-10 col-xxl-8 px-4 py-5">
  <div class="row align-items-center  ">
    <div class="col-lg-7 text-center text-lg-start">
      <h1 class="display-4 fw-bold lh-1 text-body-emphasis mb-3">Справки 086/у</h1>
      <p class="col-lg-10 fs-4">Медицинская справка 086у - официальный документ, 
        предъявление которого требуется в соответствии с законодательством рф 
        при поступлении в ВУЗ, колледж (средние и средне-специальные учебные 
        заведения), а также при устройстве в государственные и некоторые 
        коммерческие компании.</p>

        {% for sale in sale_info %}
        {% if sale.choice  == 'spravki:spravki_086' %}
        <div class="p-5 text-center bg-light rounded-3">
          <h1 class="text-danger text-body-emphasis">АКЦИЯ</h1>
          <p class="lead">
            {{ sale.text|linebreaks }}
            Дейсивует до {{ sale.pub_date }}
          </p>
        </div>
        {% endif %}
        {% endfor %}
    

    </div>

    <div class="col-md-10 mx-auto col-lg-5">
      <div class="d-flex flex-column flex-md-row p-4 gap-4 py-md-5 align-items-center justify-content-center">
        <div class="list-group">

          {% for pric in price %}
          <a href="{% url 'spravki:spravki_086_datail' pric.choice %}" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
            <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-check-square" viewBox="0 0 16 16">
              <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
              <path d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.235.235 0 0 1 .02-.022z"/>
            </svg>
            <div class="d-flex gap-2 w-100 justify-content-between">
              <div>
                <h6 class="mb-0">{{ pric.title }}</h6>
                <p class="mb-0 opacity-75">Время оформления 20 минут</p>
              </div>
              <h6 class="text-nowrap">{{ pric.price }} руб.</h6>
            </div>
          </a>
          {% endfor %}

        </div>
      </div>
    </div>
  </div>
</div>

  <div class="container marketing">


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="container-fluid">
            <div class="row">
              <div class="col">
                
                <img class="img-fluid rounded float-start p-3" src="{% static 'media/gai2.webp' %}" alt="" width="420">
                <p class="lead">
                  
                  <h2>Сделать справку 086/у в Москве в медцентре "МедикаФарм"</h2>
                  <br>&nbsp;&nbsp;&nbsp;&nbsp;Заключение врачебной комиссии о здоровье 
                  человека требуется для работы, поступления в вуз, учебы по медицинским 
                  направлениям, юридической профессиональной деятельности. В нашем 
                  центре вы можете оформить справку 086 у оперативно и недорого. У 
                  нас ведут прием все специалисты, чье заключение потребуется для 
                  документа. Тут же вы сможете пройти все необходимые анализы и 
                  обследования (лабораторные анализы крови и мочи, флюорография, 
                  ЭЭК и т.д.).

                  <br>&nbsp;&nbsp;&nbsp;&nbsp;<h2>Когда актуальна форма 086 у?</h2>

                      <br>&nbsp;&nbsp;&nbsp;&nbsp;Документы потребуются абитуриентам, 
                      которые планируют поступление, а также лицам для официального 
                      трудоустройства. В зависимости от специализации будет меняться 
                      перечень докторов и необходимых исследований. В нашем медицинском 
                      центре вы можете получить заключение о состоянии здоровья по 
                      следующим направлениям:

                      <br>&nbsp;&nbsp;&nbsp;&nbsp;<li>
                        для поступления в вуз;
                      </li>
                      <li>
                        для оформления на работу;
                      </li>
                      <li>
                        для обучения по медицинским направлениям;
                      </li>
                      <li>
                        для работы на должности судьи;
                      </li>
                      <li>
                        документ на английском языке.
                      </li>
                        
                </p>
              </div>
            </div>
          </div>
      </div>


    

    <!-- /END THE FEATURETTES -->
<hr class="featurette-divider">
<div class="row featurette">
<h1 class="display-4 fw-normal">Схема проезда</h1>
<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A32923ec50c84b444ea0967fa8cf5cf53e407a7d3aa3bea5c496b066b18a7b3fd&amp;width=1017&amp;height=570&amp;lang=ru_RU&amp;scroll=true"></script>
</div>
</div>


{% endblock %}

main_sait/templates/spravki/spravki_sport.html
{% extends 'base.html' %}
{% load static %}


{% block title%}
Справки для спорта в Медицинский центр МедикаФарм
{% endblock %}

{% block content %}


<div class="container col-xl-10 col-xxl-8 px-4 py-5">
  <div class="row align-items-center  ">
    <div class="col-lg-7 text-center text-lg-start">
      <h1 class="display-4 fw-bold lh-1 text-body-emphasis mb-3">Справка для занятий спортом</h1>
      <p class="col-lg-10 fs-4">Подтверждение отсутствия противопоказаний и 
        ограничений к физическим нагрузкам. Медицинский документ выдается 
        как взрослым, так и детям.</p>

        {% for sale in sale_info %}
        {% if sale.choice  == 'spravki:spravki_sport' %}
        <div class="p-5 text-center bg-light rounded-3">
          <h1 class="text-danger text-body-emphasis">АКЦИЯ</h1>
          <p class="lead">
            {{ sale.text|linebreaks }}
            Дейсивует до {{ sale.pub_date }}
          </p>
        </div>
        {% endif %}
        {% endfor %}

    </div>
    <div class="col-md-10 mx-auto col-lg-5">
      <div class="d-flex flex-column flex-md-row p-4 gap-4 py-md-5 align-items-center justify-content-center">
        <div class="list-group">

          {% for pric in price %}
          <a href="{% url 'spravki:spravki_sport_datail' pric.choice %}" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
            <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-check-square" viewBox="0 0 16 16">
              <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
              <path d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.235.235 0 0 1 .02-.022z"/>
            </svg>
            <div class="d-flex gap-2 w-100 justify-content-between">
              <div>
                <h6 class="mb-0">{{ pric.title }}</h6>
                <p class="mb-0 opacity-75">Время оформления 20 минут</p>
              </div>
              <h6 class="text-nowrap">{{ pric.price }} руб.</h6>
            </div>
          </a>
          {% endfor %}

        </div>
      </div>
    </div>
  </div>
</div>

  <div class="container marketing">


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="container-fluid">
            <div class="row">
              <div class="col">
                
                <img class="img-fluid rounded float-start p-3" src="{% static 'media/gai2.webp' %}" alt="" width="420">
                <p class="lead">
                  
                  <h2>Кому понадобится справка для занятия спортом формы 073/у?</h2>
                  <br>&nbsp;&nbsp;&nbsp;&nbsp;Но, как и любому делу, к занятиям спортом 
                  надо подходить с умом, так чтобы это пошло на пользу, а не во вред. 
                  Прежде чем приступить к занятиям, тем или иным видам спорта,  вас 
                  попросят предъявить справку формы 073/у.

                      <br>&nbsp;&nbsp;&nbsp;&nbsp;<li>
                        Нужна справка для спорта для участия в забеге
                      </li>
                      <li>
                        Необходима  справка для спорта для участии  в соревнованиях по бегу на марафон (42,2км), полумарафон (21,1 км)
                      </li>
                      <li>
                        Потребуется справка для спорта чтобы участвовать в любых спортивных соревнованиях
                      </li>
                      <li>
                        Требуется справка на спорт для занятия единоборствами (бокс, самбо, тайский бокс, ММА)
                      </li>
                      <li>
                        Пригодиться справка на спорт и для занятия автоспортом
                      </li>
                      <li>
                        Понадобиться справка для спорта для занятия  в любой спортивной секции
                      </li>
                      <li>
                        Нужна справка для спорта для художественной гимнастики и  фигурного катания
                      </li>

                      <br>&nbsp;&nbsp;&nbsp;&nbsp;Убедившись в том, что у вас есть такая 
                      справка, оздоровительное учреждение, организаторы соревнований и 
                      прочие заинтересованные лица, могут быть уверенны, что у вас 
                      отсутствуют противопоказания к занятиям тем или иным видом спорта. 
                      Указание в справке точного вида спорта, которым вы собираетесь 
                      заниматься, является обязательным.

                      <br>&nbsp;&nbsp;&nbsp;&nbsp;<h2>Какие могут быть противопоказания для получения справки для занятий спортом?</h2>

                      <br>&nbsp;&nbsp;&nbsp;&nbsp;Противопоказаниями для занятия спортом могут послужить:

                      <br>&nbsp;&nbsp;&nbsp;&nbsp;<li>
                        заболевания сердечно-сосудистой, дыхательной, нервной систем, которые могут привести к необратимым последствиям
                      </li>
                      <li>
                        острые заболевания
                      </li>
                      <li>
                        хронические заболевания в стадии обострения
                      </li>
                      <li>
                        патологии физического развития
                      </li>
                      <li>
                        травмы
                      </li>
                      <li>
                        некоторые патологии внутренних органов
                      </li>

                      <br>&nbsp;&nbsp;&nbsp;&nbsp;<h2>Медосмотр для справки формы 073у для занятия спортом: врачи и анализы</h2>

                      <br>&nbsp;&nbsp;&nbsp;&nbsp;Медицинский осмотр состоит из:

                      <br>&nbsp;&nbsp;&nbsp;&nbsp;<li>
                        терапевта,
                      </li>
                      <li>
                        дерматолога,
                      </li>
                      <li>
                        ЭКГ.
                      </li>

                      <br>&nbsp;&nbsp;&nbsp;&nbsp;Для допуска к занятиям некоторыми видами 
                      спорта может понадобиться сдать тот или иной анализ, например, 
                      сдача крови на RW, сдача анализов на наличие некоторых паразитарных 
                      инфекций (глисты), соскоб на энтеробиоз или общий анализ крови.

                        
                </p>
              </div>
            </div>
          </div>
      </div>


    

    <!-- /END THE FEATURETTES -->
<hr class="featurette-divider">
<div class="row featurette">
<h1 class="display-4 fw-normal">Схема проезда</h1>
<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A32923ec50c84b444ea0967fa8cf5cf53e407a7d3aa3bea5c496b066b18a7b3fd&amp;width=1017&amp;height=570&amp;lang=ru_RU&amp;scroll=true"></script>
</div>
</div>


{% endblock %}

main_sait/templates/spravki/spravki_travel.html
{% extends 'base.html' %}
{% load static %}


{% block title%}
Справки для поездок в Медицинский центр МедикаФарм
{% endblock %}

{% block content %}


<div class="container col-xl-10 col-xxl-8 px-4 py-5">
  <div class="row align-items-center  ">
    <div class="col-lg-7 text-center text-lg-start">
      <h1 class="display-4 fw-bold lh-1 text-body-emphasis mb-3">Справки для поездок</h1>
      <p class="col-lg-10 fs-4">Мы предлагаем услугу быстрого оформления 
        медицинских справок для поездки в санаторий или для выезда за 
        границу. Они необходимы для определения состояния здоровья.</p>

        {% for sale in sale_info %}
        {% if sale.choice  == 'spravki:spravki_travel' %}
        <div class="p-5 text-center bg-light rounded-3">
          <h1 class="text-danger text-body-emphasis">АКЦИЯ</h1>
          <p class="lead">
            {{ sale.text|linebreaks }}
            Дейсивует до {{ sale.pub_date }}
          </p>
        </div>
        {% endif %}
        {% endfor %}

    </div>
    <div class="col-md-10 mx-auto col-lg-5">
      <div class="d-flex flex-column flex-md-row p-4 gap-4 py-md-5 align-items-center justify-content-center">
        <div class="list-group">

          {% for pric in price %}
          <a href="{% url 'spravki:spravki_travel_datail' pric.choice %}" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
            <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-check-square" viewBox="0 0 16 16">
              <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
              <path d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.235.235 0 0 1 .02-.022z"/>
            </svg>
            <div class="d-flex gap-2 w-100 justify-content-between">
              <div>
                <h6 class="mb-0">{{ pric.title }}</h6>
                <p class="mb-0 opacity-75">Время оформления 20 минут</p>
              </div>
              <h6 class="text-nowrap">{{ pric.price }} руб.</h6>
            </div>
          </a>
          {% endfor %}

        </div>
      </div>
    </div>
  </div>
</div>

  <div class="container marketing">


    <!-- START THE FEATURETTES -->

    

    


    

    <!-- /END THE FEATURETTES -->
<hr class="featurette-divider">
<div class="row featurette">
<h1 class="display-4 fw-normal">Схема проезда</h1>
<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A32923ec50c84b444ea0967fa8cf5cf53e407a7d3aa3bea5c496b066b18a7b3fd&amp;width=1017&amp;height=570&amp;lang=ru_RU&amp;scroll=true"></script>
</div>
</div>


{% endblock %}