main_sait/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('politika-konfidencialnosti/', views.konfiden, name='konfiden'),
    path('normativno-pravovie-documenti/', views.documents, name='documents'),
    path('kontacti/', views.contact, name='contact'),
    path('katalog/', views.price, name='price'),
]

main_sait/main_sait/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('services/', include('services.urls', namespace='services')),
    path('spravki/', include('spravki.urls', namespace='spravki')),
    path('profosmotri/', include('profi.urls', namespace='profi')),
    path('knigki/', include('knigki.urls', namespace='knigki')),
    path('akzii/', include('sale.urls', namespace='sale')),
    path('statii/', include('posts.urls', namespace='posts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_sait/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('vse-statii/', views.posts_all, name='posts_all'),
    path('vse-statii/<int:post_id>/', views.post_detail, name='post_detail'),
]

main_sait/posts/models.py
from django.db import models


class Post(models.Model):
    title = models.TextField(
        'Заголовок статьи',
        help_text='Введите заголовок статьи'
    )
    overview = models.TextField(
        'Краткое описание статьи',
        help_text='Введите краткое описание статьи'
    )
    text = models.TextField(
        'Текст статьи',
        help_text='Введите текст статьи'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        db_index=True
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def __str__(self):
        return self.text[:15]

main_sait/posts/views.py
from asgiref.sync import sync_to_async
from django.shortcuts import get_object_or_404, render

from home.models import HomeTopInfo

from .models import Post
from .utils import paginator

SAIT_INFO = HomeTopInfo.objects.all()


@sync_to_async
def posts_all(request):
    template = 'posts/posts_all.html'
    info = SAIT_INFO
    posts_all = Post.objects.all()
    page_obj = paginator(request, posts_all)
    context = {
        'info': info,
        'page_obj': page_obj,
    }
    return render(request, template, context)


@sync_to_async
def post_detail(request, post_id):
    template = 'posts/posts_detail.html'
    info = SAIT_INFO
    posts = Post.objects.all()
    posts_detail = get_object_or_404(Post, pk=post_id)
    context = {
        'info': info,
        'posts': posts,
        'posts_detail': posts_detail,
    }
    return render(request, template, context)

main_sait/templates/posts/posts_all.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title%}
Статьи Медицинского центра МедикаФарм
{% endblock %}

{% block content %}
{% for inf in info %}

<div class="container p-4">

    <h2 class="pb-2 border-bottom">Все статьи</h2>

    <div class="row mb-2">
        {% for post in page_obj %}
        <div class="col-md-6">
          <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
              
              <h3 class="mb-0">{{ post.title }}</h3>
              <div class="mb-1 text-body-secondary">{{ post.pub_date|date:"d E Y" }}</div>
              <p class="card-text mb-auto">{{ post.overview }}</p>
              <a href="{% url 'posts:post_detail' post.id %}" class="stretched-link">Подробнее</a>
            </div>
            <div class="col-auto d-none d-lg-block">
                <img src="/media/{{ post.image }}" class="bd-placeholder-img" width="200" height="250" alt="">
            </div>
          </div>
        </div>
        {% endfor %}
        
      </div>

      {% include 'posts/includes/paginator.html' %}

  </div>

{% endfor %}
{% endblock %}

main_sait/templates/posts/posts_detail.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title%}
{{ posts_detail.title }} Медицинского центра МедикаФарм
{% endblock %}

{% block content %}

<div class="container p-4">

  <div class="row g-5 p-4">
    <div class="col-md-8">
      
      <article class="blog-post">
        <h2 class="blog-post-title mb-1">{{ posts_detail.title }}</h2>
        <p class="blog-post-meta">{{ posts_detail.pub_date|date:"d E Y" }}</p>
        <p>
          <img src="/media/{{ posts_detail.image }}" class="p-3 float-start" width="200" height="250" alt="">

          {{ posts_detail.text|linebreaks }}
        </p>

    </div>

    <div class="col-md-4">
      <div class="position-sticky" style="top: 2rem;">
        <div class="p-4 mb-3 bg-body-tertiary rounded">
          <h4 class="fst-italic">Другие статьи</h4>
          {% for post in posts %}
          <ol class="list-unstyled mb-0">
          <li>
          <a href="{% url 'posts:post_detail' post.id %}">{{ post.title }}</a>
           </li>
          </ol>
          {% endfor %}
        </div>

        
      </div>
    </div>
  </div>

  </div>

{% endblock %}