main_sait/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('politika-konfidencialnosti/', views.konfiden, name='konfiden'),
    path('normativno-pravovie-documenti/', views.documents, name='documents'),
    path('kontacti/', views.contact, name='contact'),
    path('katalog/', views.price, name='price'),
]

main_sait/knigki/urls.py
from django.urls import path

from . import views

app_name = 'knigki'

urlpatterns = [
    path('medknizhki/', views.medknizhki, name='medknizhki'),
]

main_sait/main_sait/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('services/', include('services.urls', namespace='services')),
    path('spravki/', include('spravki.urls', namespace='spravki')),
    path('profosmotri/', include('profi.urls', namespace='profi')),
    path('knigki/', include('knigki.urls', namespace='knigki')),
    path('akzii/', include('sale.urls', namespace='sale')),
    path('statii/', include('posts.urls', namespace='posts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_sait/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('vse-statii/', views.posts_all, name='posts_all'),
    path('vse-statii/<int:post_id>/', views.post_detail, name='post_detail'),
]

main_sait/profi/urls.py
from django.urls import path

from . import views

app_name = 'profi'

urlpatterns = [
    path('predvaritelnie/', views.predvaritelnie, name='predvaritelnie'),
    path('pereodicheskiy/', views.pereodicheskiy, name='pereodicheskiy'),
    path('vneocherednoy/', views.vneocherednoy, name='vneocherednoy'),
    path('psihiatricheskoe/', views.psihiatricheskoe, name='psihiatricheskoe'),
    path('predsmenniy/', views.predsmenniy, name='predsmenniy'),
]

main_sait/sale/urls.py
from django.urls import path

from . import views

app_name = 'sale'

urlpatterns = [
    path('', views.sale, name='sale'),
]

main_sait/templates/includes/footer.html
{% load static %}

{% for inf in info %}
<footer class="bg-light pt-5">
	<div class="container">
		<!-- Row START -->
		<div class="row g-4">

			<!-- Widget 1 START -->
			<div class="col-lg-4">
				<!-- logo -->
				<a href="/" 
         class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <img src="{% static 'media/logo.png' %}" 
             alt="" 
             width="50" 
             height="50" 
             class="d-inline-block align-text-top">
             &nbsp;
             &nbsp;
            <span class="fs-4">МедикаФарм
              <p class="h6 text-muted">Медицинский центр</p>
            </span>
      </a>
				<p class="my-3 text-muted">Медицинский центр «Медикафарм». Никакая информация на сайте не является публичной офертой, 
					если специально не оговорено обратное. Мы просим проверять важные для вас сведения по контактным телефонам. При этом 
					любая отправка любой информации нам через наш сайт означает ваше согласие на обработку нами ваших персональных данных,
					 присутствующих в ней. См. также закон о защите прав потребителей и закон об основах охраны здоровья граждан.</p>
				<p class="text-muted">Телефон: <a href="tel:{{ inf.phone_number }}" class="text-muted text-primary-hover"><i class="bi bi-telephone me-2"></i>{{ inf.phone_number }}</a> </p>
				<p class="text-muted">Частным лицам: <a href="mailto:{{ inf.email_adm }}" class="text-muted text-primary-hover"><i class="bi bi-envelope me-2"></i>{{ inf.email_adm }}</a></p>
				<p class="text-muted">Отдел продаж: <a href="mailto:{{ inf.email_sail }}" class="text-muted text-primary-hover"><i class="bi bi-envelope me-2"></i>{{ inf.email_sail }}</a></p>
			

				
				<a href="https://zakupki.mos.ru/companyProfile/supplier/2232563" 
				rel="nofollow" target="_blank" class="footer-postavshiki">
				<img alt="Мы зарегистрированы на портале поставщиков" src="{% static 'media/portal.webp' %}"></a>
			
			</div>
      		{% endfor %}       
			<!-- Widget 1 END -->

			<!-- Widget 2 START -->
			<div class="col-lg-8 ms-auto">
				<div class="row g-4">
					<!-- Link block -->
					<div class="col-6 col-md-3">
						<h5 class="mb-2 mb-md-4"><a class="nav-link" href="/">Главная страница</a></h5>
						<ul class="nav flex-column text-primary-hover">
							<li class="nav-item"><a class="nav-link text-muted" href="#">О клинике</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'home:contact' %}">Контакты</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="" data-bs-toggle="modal" data-bs-target="#otsivi">Отзывы</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'home:price' %}">Цены</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'sale:sale' %}">Акции</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'posts:posts_all' %}">Статьи</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="#">Вакансии</a></li>
						</ul>
					</div>

					<!-- Link block -->
					<div class="col-6 col-md-3">
						<h5 class="mb-2 mb-md-4">Справки</h5>
						<ul class="nav flex-column text-primary-hover">
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'spravki:gibdd' %}">ГИБДД (ГАИ) 003-В/у</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'spravki:gims' %}">Управление судами (ГИМС)</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'spravki:gsy' %}">Госслужба 001-ГС/у</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'spravki:gstayna' %}">Гостайна 989н</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'spravki:spravki_086' %}">Справка 086/у</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'spravki:student_095' %}">Справка 095/у (студентам)</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'spravki:spravki_sport' %}">Справка для спорта</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'spravki:spravki_travel' %}">Справка для поездок</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'spravki:bolnichnij' %}">Официальные больничные листы</a></li>						
						</ul>
					</div>
									
					<!-- Link block -->
					<div class="col-6 col-md-3">
						<h5 class="mb-2 mb-md-4">Врачи</h5>
						<ul class="nav flex-column text-primary-hover">
							<li class="nav-item"><a class="nav-link text-muted" href="#">Страница</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="#">Страница</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="#">Страница</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="#">Страница</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="#">Страница</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="#">Страница</a></li>
						</ul>
					</div>

					<!-- Link block -->
					<div class="col-6 col-md-3">
						<h5 class="t mb-2 mb-md-4">Услуги</h5>
						<ul class="nav flex-column text-primary-hover">
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'services:ultrasound' %}">УЗИ</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'services:rentgen' %}">Рентген</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'services:analisi' %}">Анализы</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'knigki:medknizhki' %}">Медкнижки</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'services:fluromobil' %}">Аренда флюоромобиля</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'profi:predvaritelnie' %}">Предварительный медосмотр</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'profi:pereodicheskiy' %}">Периодический медосмотр</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'profi:vneocherednoy' %}">Внеочередной медосмотр</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'profi:psihiatricheskoe' %}">Психиатрическое освидетельствование</a></li>
							<li class="nav-item"><a class="nav-link text-muted" href="{% url 'profi:predsmenniy' %}">Предрейсовый медосмотр</a></li>
						</ul>
					</div>

					
				</div>
			</div>
			<!-- Widget 2 END -->

		</div><!-- Row END -->

		<!-- Divider -->
		<hr class="mt-4 mb-0">

		<!-- Bottom footer -->
		<div class="row">
			<div class="container">
				<div class="d-lg-flex justify-content-between align-items-center py-3 text-center text-lg-start">
					<!-- copyright text -->
					<div class="text-muted text-primary-hover">© 2006-{% now 'Y' %} «Медикафарм»™®. Все права защищены.</div>
					<!-- copyright links-->
					<div class="nav mt-2 mt-lg-0">
						<ul class="list-inline text-primary-hover mx-auto mb-0">
							<li class="list-inline-item me-0"><a class="nav-link py-1 text-muted" href="{% url 'home:documents' %}">Нормативно-правовые документы</a></li>
							<li class="list-inline-item me-0"><a class="nav-link py-1 text-muted" href="{% url 'home:konfiden' %}">Политика конфиденциальности</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>

main_sait/templates/includes/header.html
{% load static %}

{% for inf in info %}
<nav class="navbar navbar-light bg-light">
  <div class="container d-flex ">
    <span class="navbar-text">
      <div class="topline-center">
        <strong><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-info-square" viewBox="0 0 16 16">
          <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
          <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
        </svg>&nbsp;&nbsp;Все справки выдаются только после прохождения 
        медицинской комиссии в полном объеме, включающей в 
        себя осмотр врачей и проведение необходимых исследований.</strong>
        <br><br> <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-clock" viewBox="0 0 16 16">
          <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
          <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z"/>
        </svg>&nbsp;&nbsp;{{ inf.work_time }}
      </div>
    </span>
  </div>
</nav>



  <div class="container p-3">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" 
         class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <img src="{% static 'media/logo.png' %}" 
             alt="" 
             width="50" 
             height="50" 
             class="d-inline-block align-text-top">
             &nbsp;
             &nbsp;
            <span class="fs-4">МедикаФарм
              <p class="h6 text-muted">Медицинский центр</p>
            </span>
      </a>

       
          <a href="tel:{{ inf.phone_number }}" 
         class="d-flex  mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <img src="{% static 'media/telephone.png' %}" 
             alt="" 
             width="30" 
             height="30" 
             class="d-inline-block">
             &nbsp;
             &nbsp;
            <span class="h4 text-muted">
              {{ inf.phone_number }}
            </span>
      </a>
{% endfor %}    
      <a href="https://yandex.ru/maps/213/moscow/?indoorLevel=1&ll=37.643734%2C55.728692&mode=routes&rtext=55.727203%2C37.646909~55.730059%2C37.641259&rtt=pd&ruri=ymapsbm1%3A%2F%2Forg%3Foid%3D145178380882~&z=17.79" 
         class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none" target="_blank">
        <img src="{% static 'media/map.png' %}" 
             alt="" 
             width="30" 
             height="30" 
             class="d-inline-block align-text-top">
             &nbsp;
             &nbsp;
            <span class="h6 text-muted">Москва, м. Павелецкая <br>
              1-й Кожевнический пер. дом 8
            </span>
      </a>


<button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
  Личный кабинет
</button>


<div class="modal fade" 
     id="staticBackdrop" 
     data-bs-backdrop="static" 
     data-bs-keyboard="false" 
     tabindex="-1" 
     aria-labelledby="staticBackdropLabel" 
     aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Личный кабинет</h1>
        <button type="button" 
                class="btn-close" 
                data-bs-dismiss="modal" 
                aria-label="Close">
          </button>
      </div>
      <div class="modal-body">
        Приносим свои извинения, страница находится в разработке!
      </div>
      <div class="modal-footer">
        <button type="button" 
                class="btn btn-secondary" 
                data-bs-dismiss="modal">
                Закрыть
          </button>
      </div>
    </div>
  </div>
</div>
      
  </div>
</div>

main_sait/templates/includes/menu.html
{% load static %}

<nav class="navbar navbar-expand-lg sticky-top bg-white navbar-light">
    <div class="container-fluid justify-content-center">
      <button class="navbar-toggler" 
              type="button" 
              data-bs-toggle="collapse" 
              data-bs-target="#navbarNavDropdown" 
              aria-controls="navbarNavDropdown" 
              aria-expanded="true" 
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-center" id="navbarNavDropdown">
        
        <ul class="navbar-nav mb-2 mb-lg-0">
          &nbsp;&nbsp;<a href="tel:{{ inf.phone_number }}" 
         class="d-flex  mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <img src="{% static 'media/telephone.png' %}" 
             alt="" 
             width="30" 
             height="30" 
             class="d-inline-block">
             </a>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" 
               href="/" 
               id="menu1" 
               role="button" 
               data-bs-toggle="dropdown" 
               aria-expanded="true">
               &nbsp;&nbsp;О нас
            </a>
            <ul class="dropdown-menu" aria-labelledby="menu1">
              <li><a class="dropdown-item" href="#">О клинике</a></li>
              <li><a class="dropdown-item" href="{% url 'home:contact' %}">Контакты</a></li>
              <li><a class="dropdown-item" href="{% url 'posts:posts_all' %}">Статьи</a></li>
              <li><a class="dropdown-item" href="" data-bs-toggle="modal" data-bs-target="#otsivi">Отзывы</a></li>
              <li><a class="dropdown-item" href="#">Вопросы врачам</a></li>
              <li><a class="dropdown-item" href="#">Коллектив</a></li>
              <li><a class="dropdown-item" href="#">Вакансии</a></li>
              <li><a class="dropdown-item" href="#">Фотогалерея</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" 
               href="#" 
               id="menu2" 
               role="button" 
               data-bs-toggle="dropdown" 
               aria-expanded="false">
               &nbsp;&nbsp;Услуги
            </a>
            <ul class="dropdown-menu" aria-labelledby="menu2">
              <li><a class="dropdown-item" href="{% url 'services:ultrasound' %}">УЗИ</a></li>
              <li><a class="dropdown-item" href="{% url 'services:rentgen' %}">Рентген</a></li>
              <li><a class="dropdown-item" href="{% url 'services:analisi' %}">Анализы</a></li>
              <li><a class="dropdown-item" href="{% url 'services:fluromobil' %}">Аренда флюоромобиля</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" 
               href="#" 
               id="menu3" 
               role="button" 
               data-bs-toggle="dropdown" 
               aria-expanded="false">
               &nbsp;&nbsp;Врачи
            </a>
            <ul class="dropdown-menu" aria-labelledby="menu3">
              <li><a class="dropdown-item" href="#">2Второе меню</a></li>
              <li><a class="dropdown-item" href="#">Второе меню</a></li>
              <li><a class="dropdown-item" href="#">Второе меню</a></li>
              <li><a class="dropdown-item" href="#">Второе меню</a></li>
              <li><a class="dropdown-item" href="#">Второе меню</a></li>
              <li><a class="dropdown-item" href="#">Второе меню</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" 
               href="#" 
               id="menu4" 
               role="button" 
               data-bs-toggle="dropdown" 
               aria-expanded="false">
               &nbsp;&nbsp;Профосмотры
            </a>
            <ul class="dropdown-menu" aria-labelledby="menu4">
              <li><a class="dropdown-item" href="{% url 'profi:predvaritelnie' %}">Предварительный медосмотр</a></li>
              <li><a class="dropdown-item" href="{% url 'profi:pereodicheskiy' %}">Периодический медосмотр</a></li>
              <li><a class="dropdown-item" href="{% url 'profi:vneocherednoy' %}">Внеочередной медосмотр</a></li>
              <li><a class="dropdown-item" href="{% url 'profi:psihiatricheskoe' %}">Психиатрическое освидетельствование</a></li>
              <li><a class="dropdown-item" href="{% url 'profi:predsmenniy' %}">Предрейсовый медосмотр</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" 
               href="#" 
               id="menu10" 
               role="button" 
               data-bs-toggle="dropdown" 
               aria-expanded="false">
               &nbsp;&nbsp;Справки
            </a>
            <ul class="dropdown-menu" aria-labelledby="menu10">
              <li><a class="dropdown-item" href="{% url 'spravki:gibdd' %}">ГИБДД (ГАИ) 003-В/у</a></li>
              <li><a class="dropdown-item" href="{% url 'spravki:gims' %}">Управление судами (ГИМС)</a></li>
              <li><a class="dropdown-item" href="{% url 'spravki:gsy' %}">Госслужба 001-ГС/у</a></li>
              <li><a class="dropdown-item" href="{% url 'spravki:gstayna' %}">Гостайна 989н</a></li>
              <li><a class="dropdown-item" href="{% url 'spravki:spravki_086' %}">Справка 086/у</a></li>
              <li><a class="dropdown-item" href="{% url 'spravki:student_095' %}">Справка 095/у (студентам)</a></li>
              <li><a class="dropdown-item" href="{% url 'spravki:spravki_sport' %}">Справка для спорта</a></li>
              <li><a class="dropdown-item" href="{% url 'spravki:spravki_travel' %}">Справка для поездок</a></li>
              <li><a class="dropdown-item" href="{% url 'spravki:bolnichnij' %}">Официальные больничные листы</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="{% url 'knigki:medknizhki' %}" class="nav-link px-2 text-blak">Медкнижки</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'home:price' %}" class="nav-link px-2 text-blak">Цены</a>
          </li>
          <li class="nav-item text-bg-danger rounded-3">
            <a href="{% url 'sale:sale' %}" class="nav-link px-2 text-white">Акции</a> 
          </li>
          </ul>  
          &nbsp;&nbsp;
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Поиск..." aria-label="Поиск">
              <button class="btn btn-outline-success" type="submit">Поиск</button>
            </form> 
           
                       
      </div>
    </div>
  </nav>

  <div class="modal fade" id="otsivi" tabindex="-1" aria-labelledby="otsiviLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="otsiviLabel">Отзывы на Яндекс</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="container-fluid">
            <div class="row">
          <div style="width:560px;height:400px;overflow:hidden;position:relative;"><iframe style="width:100%;height:100%;border-radius:8px;box-sizing:border-box" src="https://yandex.ru/maps-reviews-widget/145178380882?comments"></iframe><a href="https://yandex.ru/maps/org/medikafarm/145178380882/" target="_blank" style="box-sizing:border-box;text-decoration:none;color:#b3b3b3;font-size:10px;font-family:YS Text,sans-serif;padding:0 20px;position:absolute;bottom:8px;width:100%;text-align:center;left:0;overflow:hidden;text-overflow:ellipsis;display:block;max-height:14px;white-space:nowrap;padding:0 16px;box-sizing:border-box">Медикафарм на карте Москвы — Яндекс Карты</a></div>        </div>
        </div>
        </div>
      </div>
    </div>
  </div>